### ISSUE TITLE
Not Seeing the initital button on a dataobject

### ISSUE THREAD

**Issue by tomeralmog** [silverstripe-australia/advancedworkflow#202]
Hi,
Thank you for the addon, it looks perfect to what I need to implement.
I am using SilverStripe vesrion (version 3.1.6) and latest version of advancedworkflow
My site is build mostly on data objects.
I have assigned both object and model admin in the .yml file as described in the documentation:
```
MyObject:
    extensions:
        - WorkflowApplicable
MyObjectAdmin:
    extensions:
        - AdvancedWorkflowExtension
```
I have also assign the workflow in the workflow tab of the object.
I am using the template review and approve workflow.

While I see the button to start a workflow when editing a page, the buttons doesn't show up for the dataobject. Do I need to add code in the object level, or modify the template workflow to work with data objects?
Thank you!
